namespace LakeCountrySpanish.Web.Models.Entities;

/// <summary>
/// Type of assignment exercise.
/// </summary>
public enum AssignmentType
{
    FillInTheBlank,
    MultipleChoice,
    Translation,
    Matching,
    ShortAnswer,
    Listening,
    Reading,
    Mixed
}

/// <summary>
/// Status of an assignment in the review workflow.
/// </summary>
public enum AssignmentStatus
{
    Draft,
    PendingReview,
    Approved,
    Rejected,
    Archived
}

/// <summary>
/// Represents an assignment that can be assigned to students.
/// </summary>
public class Assignment
{
    public int Id { get; set; }

    /// <summary>
    /// Assignment title
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Brief description/instructions for the student
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// CEFR level (A1, A2, B1, B2, C1, C2)
    /// </summary>
    public string CefrLevel { get; set; } = "A1";

    /// <summary>
    /// Optional curriculum topic this assignment covers
    /// </summary>
    public int? CurriculumTopicId { get; set; }

    /// <summary>
    /// Type of assignment
    /// </summary>
    public AssignmentType Type { get; set; }

    /// <summary>
    /// Current status in the review workflow
    /// </summary>
    public AssignmentStatus Status { get; set; } = AssignmentStatus.Draft;

    /// <summary>
    /// JSON containing the questions/exercises
    /// Structure varies by type but generally:
    /// [{ "id": 1, "question": "...", "options": [...], "correctAnswer": "..." }]
    /// </summary>
    public string QuestionsJson { get; set; } = "[]";

    /// <summary>
    /// JSON containing the correct answers (for grading)
    /// [{ "id": 1, "answer": "...", "acceptableAnswers": [...], "explanation": "..." }]
    /// </summary>
    public string AnswersJson { get; set; } = "[]";

    /// <summary>
    /// Total points possible for this assignment
    /// </summary>
    public int TotalPoints { get; set; } = 10;

    /// <summary>
    /// Bonus points for perfect score
    /// </summary>
    public int BonusPoints { get; set; } = 0;

    /// <summary>
    /// Estimated time to complete in minutes
    /// </summary>
    public int EstimatedMinutes { get; set; } = 10;

    /// <summary>
    /// Whether this assignment was generated by AI
    /// </summary>
    public bool IsAiGenerated { get; set; }

    /// <summary>
    /// The prompt used to generate this assignment (if AI-generated)
    /// </summary>
    public string? GenerationPrompt { get; set; }

    /// <summary>
    /// When the assignment was reviewed (if applicable)
    /// </summary>
    public DateTime? ReviewedAt { get; set; }

    /// <summary>
    /// Who reviewed the assignment
    /// </summary>
    public string? ReviewedById { get; set; }

    /// <summary>
    /// Notes from the reviewer
    /// </summary>
    public string? ReviewNotes { get; set; }

    /// <summary>
    /// Who created the assignment
    /// </summary>
    public string? CreatedById { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    // Navigation properties
    public virtual CurriculumTopic? CurriculumTopic { get; set; }
    public virtual ApplicationUser? ReviewedBy { get; set; }
    public virtual ApplicationUser? CreatedBy { get; set; }
    public virtual ICollection<StudentAssignment> StudentAssignments { get; set; } = new List<StudentAssignment>();
    public virtual ICollection<AssignmentSubmission> Submissions { get; set; } = new List<AssignmentSubmission>();
}
