namespace LakeCountrySpanish.Web.Models.Entities;

/// <summary>
/// Where a media asset originated. New sources can be added without schema
/// changes — each source has a corresponding adapter that handles search and
/// import. AI-generated assets carry their prompt/model so they can be
/// regenerated or audited.
/// </summary>
public enum MediaSource
{
    /// <summary>Uploaded directly by an admin / teacher.</summary>
    Upload = 0,
    Pixabay = 1,
    Unsplash = 2,
    /// <summary>Generated by a local AI model (deferred to Phase 4).</summary>
    AIGenerated = 3
}

/// <summary>
/// Curriculum-specific categorization of a media asset. Used to filter the
/// media library when authoring artifacts.
/// </summary>
public enum MediaCategory
{
    Uncategorized = 0,
    /// <summary>Lola the llama and brand mascot variants.</summary>
    Mascot = 1,
    /// <summary>Photos of Spanish-speaking cultures, food, places, traditions.</summary>
    CulturalImage = 2,
    /// <summary>Single-object illustrations for vocabulary flashcards.</summary>
    FlashcardArt = 3,
    /// <summary>Decorations and content art for worksheets.</summary>
    WorksheetIllustration = 4,
    /// <summary>Bingo cells, memory-match pairs, board tiles, game pieces.</summary>
    GameAsset = 5,
    /// <summary>Decorative page backgrounds and borders.</summary>
    Background = 6,
    /// <summary>Small functional icons (checkmark, arrow, star).</summary>
    Icon = 7,
    /// <summary>Borders, dividers, banners, ornamental flourishes.</summary>
    Decorative = 8,
    Other = 99
}

/// <summary>
/// An imported or uploaded image stored locally. Lifecycle is tracked via
/// <see cref="MediaUsage"/> records so we can find unused assets, prevent
/// orphan deletes, and audit which artifacts use which media.
///
/// Borrowed structurally from the Ellis Hope Foundation media library pattern
/// (see <c>Services/PdfService.cs</c> and <c>Models/Domain/Media.cs</c> in
/// the EHF repo). Adapted for LCS-specific source and category enums.
/// </summary>
public class MediaAsset
{
    public int Id { get; set; }

    /// <summary>
    /// Original filename at the time of upload / import (preserved for display).
    /// </summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Web-accessible relative path to the stored file, e.g.
    /// "/uploads/media/pixabay/123456.jpg".
    /// </summary>
    public string FilePath { get; set; } = string.Empty;

    /// <summary>
    /// Where this asset came from (Upload, Pixabay, Unsplash, AIGenerated).
    /// </summary>
    public MediaSource Source { get; set; }

    /// <summary>
    /// LCS curriculum category (Mascot, FlashcardArt, etc.). Defaults to
    /// Uncategorized for uploads where the admin hasn't yet assigned one.
    /// </summary>
    public MediaCategory Category { get; set; } = MediaCategory.Uncategorized;

    /// <summary>
    /// External source's identifier (e.g. Pixabay photo id). Null for uploads.
    /// </summary>
    public string? SourceId { get; set; }

    /// <summary>
    /// Original source URL for attribution and debugging. Null for uploads.
    /// </summary>
    public string? SourceUrl { get; set; }

    /// <summary>
    /// Photographer / creator name for attribution display. Null for uploads.
    /// </summary>
    public string? Photographer { get; set; }

    /// <summary>
    /// Photographer's profile URL at the source. Linked from the binder
    /// attribution page. Null for uploads.
    /// </summary>
    public string? PhotographerUrl { get; set; }

    /// <summary>
    /// License identifier, e.g. "Pixabay License", "Unsplash License",
    /// "Public Domain", "Internal LCS".
    /// </summary>
    public string? LicenseType { get; set; }

    /// <summary>
    /// Free-form license note or full license text snippet, where required by
    /// the source's terms of service.
    /// </summary>
    public string? LicenseText { get; set; }

    /// <summary>
    /// File size in bytes.
    /// </summary>
    public long FileSize { get; set; }

    /// <summary>
    /// MIME type, e.g. "image/jpeg", "image/png", "image/svg+xml".
    /// </summary>
    public string MimeType { get; set; } = string.Empty;

    /// <summary>
    /// Accessibility alt text. Required for any asset surfaced to students;
    /// admin UI prompts for it on import / upload.
    /// </summary>
    public string? AltText { get; set; }

    /// <summary>
    /// Display title for the asset, separate from the file name.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Comma-separated tags for filtering and search.
    /// </summary>
    public string? Tags { get; set; }

    public int Width { get; set; }
    public int Height { get; set; }

    /// <summary>
    /// SHA256 of the file bytes for duplicate detection.
    /// </summary>
    public string FileHash { get; set; } = string.Empty;

    /// <summary>
    /// JSON dictionary of resized variants:
    /// { "thumb": "/uploads/media/thumbnails/123_thumb_150x150.jpg",
    ///   "web":   "/uploads/media/thumbnails/123_web_800x600.jpg" }.
    /// Flexible structure so we can add sizes without schema changes.
    /// </summary>
    public string ThumbnailsJson { get; set; } = "{}";

    public DateTime UploadedDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// FK to <see cref="ApplicationUser"/> who uploaded or imported the asset.
    /// </summary>
    public string UploadedById { get; set; } = string.Empty;

    /// <summary>
    /// Prompt used to generate this asset, when <see cref="Source"/> is
    /// <see cref="MediaSource.AIGenerated"/>. Stored for regeneration and
    /// traceability.
    /// </summary>
    public string? AiPrompt { get; set; }

    /// <summary>
    /// AI model identifier, when <see cref="Source"/> is
    /// <see cref="MediaSource.AIGenerated"/>. Example: "stable-diffusion-xl",
    /// "flux-schnell".
    /// </summary>
    public string? AiModel { get; set; }

    // Navigation properties
    public virtual ICollection<MediaUsage> Usages { get; set; } = new List<MediaUsage>();
}
